<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <AssemblyName>LoadCatalogFix</AssemblyName>
    <Product>Fix addressables load catalog</Product>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>LoadCatalogFix</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
  </ItemGroup>
</Project>
