<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.1.0" PrivateAssets="all" />
  </ItemGroup>
  
  <PropertyGroup>
    <Thunderstore>true</Thunderstore>
    <TargetFramework>net481</TargetFramework>
    <AssemblyName>ButterandCream.SFK.DemolishAll</AssemblyName>
    <Product>Ability to demolish any city building</Product>
    <Version>1.0.1</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>DemolishAll</RootNamespace>
  </PropertyGroup>

</Project>
