<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.1.0" PrivateAssets="all" />
  </ItemGroup>
  
  <PropertyGroup>
    <Thunderstore>true</Thunderstore>
    <ThunderstoreDescription>Allows you to demolish any building at anytime with banishes (except the castle)</ThunderstoreDescription>
    <TargetFramework>net481</TargetFramework>
    <AssemblyName>DemolishAll</AssemblyName>
    <Product>DemolishAll</Product>
    <Version>1.0.3</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>DemolishAll</RootNamespace>
  </PropertyGroup>

</Project>
