<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.1.0" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <Thunderstore>true</Thunderstore>
    <ThunderstoreDescription>A UI Library to allow easy creation of various components</ThunderstoreDescription>
    <TargetFramework>net481</TargetFramework>
    <AssemblyName>ButterandCream.SFK.UILib</AssemblyName>
    <Product>SFK UILib</Product>
    <Version>1.0.1</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SFKUILib</RootNamespace>
  </PropertyGroup>

</Project>
