<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.1.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <SubType>Component</SubType>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <Thunderstore>true</Thunderstore>
    <TargetFramework>net481</TargetFramework>
    <AssemblyName>ButterandCream.SFK.UILib</AssemblyName>
    <Product>A UI library for SFK</Product>
    <Version>1.0.1</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SFKUILib</RootNamespace>
  </PropertyGroup>

</Project>
