using SuperFantasyKingdom;
using SuperFantasyKingdom.MonsterEvent;
using SuperFantasyKingdom.Spawner;
using SuperFantasyKingdom.Status;
using SuperFantasyKingdom.Tavern;
using SuperFantasyKingdom.TitleScreen;
using SuperFantasyKingdom.UI;
using SuperFantasyKingdom.Weather;

namespace SFKMod
{
    public static class Instances
    {
        public static AnimalSpawner AnimalSpawner => AnimalSpawner.Instance;
        public static BossSpawner BossSpawner => BossSpawner.Instance;
        public static DamageNumberSpawner DamageNumberSpawner => DamageNumberSpawner.Instance;
        public static DroppedShardSpawner DroppedShardSpawner => DroppedShardSpawner.Instance;
        public static FishSpawner FishSpawner => FishSpawner.Instance;
        public static MonsterSpawner MonsterSpawner => MonsterSpawner.Instance;
        public static ProvokedSpawner ProvokedSpawner => ProvokedSpawner.Instance;
        public static WorldBuildingSpawner WorldBuildingSpawner => WorldBuildingSpawner.Instance;
        public static WorldMonsterSpawner WorldMonsterSpawner => WorldMonsterSpawner.Instance;
        public static WorldResourceSpawner WorldResourceSpawner => WorldResourceSpawner.Instance;
        public static EOSManager EOSManager => EOSManager.Instance;
        public static GOGManager GOGManager => GOGManager.Instance;
        public static HappinessManager HappinessManager => HappinessManager.Instance;
        public static MainManager MainManager => MainManager.Instance;
        public static SteamManager SteamManager => SteamManager.Instance;
        public static AchievementManager AchievementManager => AchievementManager.Instance;
        public static AddressablesManager AddressablesManager => AddressablesManager.Instance;
        public static AlertManager AlertManager => AlertManager.Instance;
        public static BoostManager BoostManager => BoostManager.Instance;
        public static ChallengeManager ChallengeManager => ChallengeManager.Instance;
        public static CityManager CityManager => CityManager.Instance;
        public static CityRulesManager CityRulesManager => CityRulesManager.Instance;
        public static CombatManager CombatManager => CombatManager.Instance;
        public static CursorManager CursorManager => CursorManager.Instance;
        public static DaytimeManager DaytimeManager => DaytimeManager.Instance;
        public static DepositManager DepositManager => DepositManager.Instance;
        public static DialogueManager DialogueManager => DialogueManager.Instance;
        public static EffectKeywordDictionaryManager EffectKeywordDictionaryManager => EffectKeywordDictionaryManager.Instance;
        public static FaithManager FaithManager => FaithManager.Instance;
        public static FlagManager FlagManager => FlagManager.Instance;
        public static FogOfWarManager FogOfWarManager => FogOfWarManager.Instance;
        public static FontManager FontManager => FontManager.Instance;
        public static GameDataManager GameDataManager => GameDataManager.Instance;
        public static GameEventManager GameEventManager => GameEventManager.Instance;
        public static GameManager GameManager => GameManager.Instance;
        public static GamepadManager GamepadManager => GamepadManager.Instance;
        public static GridManager GridManager => GridManager.Instance;
        public static InvasionManager InvasionManager => InvasionManager.Instance;
        public static ItemManager ItemManager => ItemManager.Instance;
        public static JobManager JobManager => JobManager.Instance;
        public static ModManager ModManager => ModManager.Instance;
        public static MonsterPoolManager MonsterPoolManager => MonsterPoolManager.Instance;
        public static MusicManager MusicManager => MusicManager.Instance;
        public static ObjectPoolManager ObjectPoolManager => ObjectPoolManager.Instance;
        public static OverlayManager OverlayManager => OverlayManager.Instance;
        public static PathManager PathManager => PathManager.Instance;
        public static PermanentDataManager PermanentDataManager => PermanentDataManager.Instance;
        public static PrefabsManager PrefabsManager => PrefabsManager.Instance;
        public static ProjectilePoolManager ProjectilePoolManager => ProjectilePoolManager.Instance;
        public static RaceDataManager RaceDataManager => RaceDataManager.Instance;
        public static RaceEventManager RaceEventManager => RaceEventManager.Instance;
        public static RaceManager RaceManager => RaceManager.Instance;
        public static RelicManager RelicManager => RelicManager.Instance;
        public static ResourceManager ResourceManager => ResourceManager.Instance;
        public static RichPresenceManager RichPresenceManager => RichPresenceManager.Instance;
        public static SaveManager SaveManager => SaveManager.Instance;
        public static SettingsManager SettingsManager => SettingsManager.Instance;
        public static StatisticsManager StatisticsManager => StatisticsManager.Instance;
        public static SteamLeaderboardManager SteamLeaderboardManager => SteamLeaderboardManager.Instance;
        public static TaxManager TaxManager => TaxManager.Instance;
        public static TooltipManager TooltipManager => TooltipManager.Instance;
        public static TutorialManager TutorialManager => TutorialManager.Instance;
        public static UIManager UIManager => UIManager.Instance;
        public static UnitManager UnitManager => UnitManager.Instance;
        public static UnlockedUnitsManager UnlockedUnitsManager => UnlockedUnitsManager.Instance;
        public static WallManager WallManager => WallManager.Instance;
        public static WorldManager WorldManager => WorldManager.Instance;
        public static MonsterEventManager MonsterEventManager => MonsterEventManager.Instance;
        public static StatusComboManager StatusComboManager => StatusComboManager.Instance;
        public static TavernFoodManager TavernFoodManager => TavernFoodManager.Instance;
        public static TavernManager TavernManager => TavernManager.Instance;
        public static TavernPartyManager TavernPartyManager => TavernPartyManager.Instance;
        public static TavernSaveManager TavernSaveManager => TavernSaveManager.Instance;
        public static TitleScreenHeroSelectionManager TitleScreenHeroSelectionManager => TitleScreenHeroSelectionManager.Instance;
        public static TitleScreenManager TitleScreenManager => TitleScreenManager.Instance;
        public static UICatalogManager UICatalogManager => UICatalogManager.Instance;
        public static WeatherManager WeatherManager => WeatherManager.Instance;
        public static GameCamera GameCamera => GameCamera.Instance;
        public static Helper Helper => Helper.Instance;
        public static RoadBuilder RoadBuilder => RoadBuilder.Instance;
        public static TavernCaptures TavernCaptures => TavernCaptures.Instance;
        public static TavernDirector TavernDirector => TavernDirector.Instance;
        public static TavernGraph TavernGraph => TavernGraph.Instance;
        public static TavernLevelUp TavernLevelUp => TavernLevelUp.Instance;
        public static TavernSound TavernSound => TavernSound.Instance;
        public static TavernSummary TavernSummary => TavernSummary.Instance;
        public static TavernUnits TavernUnits => TavernUnits.Instance;
        public static TitleScreenChallenges TitleScreenChallenges => TitleScreenChallenges.Instance;

    }
}
