using SuperFantasyKingdom;
using SuperFantasyKingdom.MonsterEvent;
using SuperFantasyKingdom.Status;
using SuperFantasyKingdom.Tavern;
using SuperFantasyKingdom.TitleScreen;
using SuperFantasyKingdom.UI;
using SuperFantasyKingdom.Weather;

namespace SFKMod
{
    public static class Managers
    {
        public static EOSManager EOS => EOSManager.Instance;
        public static GOGManager GOG => GOGManager.Instance;
        public static HappinessManager Happiness => HappinessManager.Instance;
        public static MainManager Main => MainManager.Instance;
        public static SteamManager Steam => SteamManager.Instance;
        public static AchievementManager Achievement => AchievementManager.Instance;
        public static AddressablesManager Addressables => AddressablesManager.Instance;
        public static AlertManager Alert => AlertManager.Instance;
        public static BoostManager Boost => BoostManager.Instance;
        public static ChallengeManager Challenge => ChallengeManager.Instance;
        public static CityManager City => CityManager.Instance;
        public static CityRulesManager CityRules => CityRulesManager.Instance;
        public static CombatManager Combat => CombatManager.Instance;
        public static CursorManager Cursor => CursorManager.Instance;
        public static DaytimeManager Daytime => DaytimeManager.Instance;
        public static DepositManager Deposit => DepositManager.Instance;
        public static DialogueManager Dialogue => DialogueManager.Instance;
        public static EffectKeywordDictionaryManager EffectKeywordDictionary => EffectKeywordDictionaryManager.Instance;
        public static FaithManager Faith => FaithManager.Instance;
        public static FlagManager Flag => FlagManager.Instance;
        public static FogOfWarManager FogOfWar => FogOfWarManager.Instance;
        public static FontManager Font => FontManager.Instance;
        public static GameDataManager GameData => GameDataManager.Instance;
        public static GameEventManager GameEvent => GameEventManager.Instance;
        public static GameManager Game => GameManager.Instance;
        public static GamepadManager Gamepad => GamepadManager.Instance;
        public static GridManager Grid => GridManager.Instance;
        public static InvasionManager Invasion => InvasionManager.Instance;
        public static ItemManager Item => ItemManager.Instance;
        public static JobManager Job => JobManager.Instance;
        public static ModManager Mod => ModManager.Instance;
        public static MonsterPoolManager MonsterPool => MonsterPoolManager.Instance;
        public static MusicManager Music => MusicManager.Instance;
        public static ObjectPoolManager ObjectPool => ObjectPoolManager.Instance;
        public static OverlayManager Overlay => OverlayManager.Instance;
        public static PathManager Path => PathManager.Instance;
        public static PermanentDataManager PermanentData => PermanentDataManager.Instance;
        public static PrefabsManager Prefabs => PrefabsManager.Instance;
        public static ProjectilePoolManager ProjectilePool => ProjectilePoolManager.Instance;
        public static RaceDataManager RaceData => RaceDataManager.Instance;
        public static RaceEventManager RaceEvent => RaceEventManager.Instance;
        public static RaceManager Race => RaceManager.Instance;
        public static RelicManager Relic => RelicManager.Instance;
        public static ResourceManager Resource => ResourceManager.Instance;
        public static RichPresenceManager RichPresence => RichPresenceManager.Instance;
        public static SaveManager Save => SaveManager.Instance;
        public static SettingsManager Settings => SettingsManager.Instance;
        public static StatisticsManager Statistics => StatisticsManager.Instance;
        public static SteamLeaderboardManager SteamLeaderboard => SteamLeaderboardManager.Instance;
        public static TaxManager Tax => TaxManager.Instance;
        public static TooltipManager Tooltip => TooltipManager.Instance;
        public static TutorialManager Tutorial => TutorialManager.Instance;
        public static UIManager UI => UIManager.Instance;
        public static UnitManager Unit => UnitManager.Instance;
        public static UnlockedUnitsManager UnlockedUnits => UnlockedUnitsManager.Instance;
        public static WallManager Wall => WallManager.Instance;
        public static WorldManager World => WorldManager.Instance;
        public static MonsterEventManager MonsterEvent => MonsterEventManager.Instance;
        public static StatusComboManager StatusCombo => StatusComboManager.Instance;
        public static TavernFoodManager TavernFood => TavernFoodManager.Instance;
        public static TavernManager Tavern => TavernManager.Instance;
        public static TavernPartyManager TavernParty => TavernPartyManager.Instance;
        public static TavernSaveManager TavernSave => TavernSaveManager.Instance;
        public static TitleScreenHeroSelectionManager TitleScreenHeroSelection => TitleScreenHeroSelectionManager.Instance;
        public static TitleScreenManager TitleScreen => TitleScreenManager.Instance;
        public static UICatalogManager UICatalog => UICatalogManager.Instance;
        public static WeatherManager Weather => WeatherManager.Instance;
    }
}
