<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <AssemblyName>SFKMod</AssemblyName>
    <Product>A Bunch of SFK modding tests</Product>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SFKMod</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Patches\" />
  </ItemGroup>
  
</Project>
