<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Thunderstore>true</Thunderstore>
    <ThunderstoreDescription>Make those pesky workers keep working.</ThunderstoreDescription>
    <TargetFramework>net481</TargetFramework>
    <AssemblyName>No_Breaks</AssemblyName>
    <Product>Workers never stop.</Product>
    <Version>1.0.2</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>No_Breaks</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
  </ItemGroup>

</Project>
